name: Build OpenWrt for OneCloud (WS1608)

on:
  workflow_dispatch:
    inputs:
      lede_branch:
        description: 'LEDE 分支名称'
        required: true
        default: 'master'
      target:
        description: '目标架构'
        required: true
        default: 'arm'
      subtarget:
        description: '子架构'
        required: true
        default: 'amlogic'
      profile:
        description: '设备配置文件'
        required: true
        default: 'onecloud'
      make_jobs:
        description: '并行编译任务数'
        required: false
        default: '2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LEDE repository
        uses: actions/checkout@v4
        with:
          repository: coolsnowwolf/lede
          ref: ${{ github.event.inputs.lede_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache gawk git subversion \
            libncurses5-dev libssl-dev python3 python3-setuptools python3-pip \
            unzip zlib1g-dev wget rsync gcc g++ make gettext automake \
            libtool binutils bzip2 file g++-multilib bc \
            bison flex gperf python3-venv zstd libelf-dev u-boot-tools

      - name: Prepare build environment
        run: |
          git clone https://github.com/coolsnowwolf/lede.git lede-src
          cd lede-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build
        run: |
          cd lede-src
          make defconfig
          make menuconfig
          # 选择目标设备配置文件
          make target/${{ github.event.inputs.target }}-${{ github.event.inputs.subtarget }}-${{ github.event.inputs.profile }}.config

      - name: Build firmware
        run: |
          cd lede-src
          make -j${{ github.event.inputs.make_jobs }} V=s

      - name: Generate ImageBuilder
        run: |
          cd lede-src
          make imagebuilder

      - name: Upload firmware and ImageBuilder
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: |
            lede-src/bin/targets/${{ github.event.inputs.target }}/${{ github.event.inputs.subtarget }}/imagebuilder/*
            lede-src/bin/targets/${{ github.event.inputs.target }}/${{ github.event.inputs.subtarget }}/*.{bin,img}
